# Generated by Django 5.1.6 on 2025-02-17 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_cylinderbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_type', models.CharField(choices=[('Domestic', 'Domestic'), ('commercial', 'Commercial')], max_length=20)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CreditCard', 'Credit Card'), ('COD', 'Cash on Delivery')], max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.deliverystaff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
